### ISSUE TITLE
The df-server-cf fails to start when run locally due to SSL handshake failure

### ISSUE THREAD

**Issue by ashwgupt** [spring-cloud/spring-cloud-dataflow-server-cloudfoundry#206]
I have been using the cloud-dataflow-server-local successfully so far and have switched to use the dataflow-server-cloudfoundry to deploy my Stream app to our PCF.

I am running the server app locally as per [document](http://docs.spring.io/spring-cloud-dataflow-server-cloudfoundry/docs/current-SNAPSHOT/reference/htmlsingle/#_running_the_server_app_locally)

However the start-up of the server application is failing with the below error:
```
[ERROR] Failed to execute goal org.springframework.boot:spring-boot-maven-plugin:1.4.1.RELEASE:run (default-cli) on project spring-cloud-dataflow-server-cloudfoundry: An exception occurred while running. null: InvocationTargetException: Error creating bean with name 'taskLauncher' defined in class path resource [org/springframework/cloud/deployer/spi/cloudfoundry/CloudFoundryDeployerAutoConfiguration.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.springframework.cloud.deployer.spi.task.TaskLauncher]: Factory method 'taskLauncher' threw exception; nested exception is reactor.core.Exceptions$ReactiveException: javax.net.ssl.SSLHandshakeException: General SSLEngine problem: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target -> [Help 1]
```

It doesn't specify the https end point with which the SSL handshake operation failed. My best guess is that, it's the Maven repository as am using our private enterprise repository.

Command `export MAVEN_REMOTE_REPOSITORIES_REPO1_URL=https://ftl...:8443/NEXUS` from the documentation is used to set the remote repo location but that may not suffice as the location for *trustStore* and *trustStorePassword* will also need to be set.

Is this possible to achieve?

**Comment by ilayaperumalg** [comment]
Just to confirm, have you set `export SPRING_CLOUD_DEPLOYER_CLOUDFOUNDRY_SKIP_SSL_VALIDATION=false` that skips SSL validation?

**Comment by ashwgupt** [comment]
Yes, these are the other export commands I've used
```
export SPRING_CLOUD_DEPLOYER_CLOUDFOUNDRY_URL=https://api.paasnpos.bip.uk.fid-intl.com/
export SPRING_CLOUD_DEPLOYER_CLOUDFOUNDRY_ORG=Paas-Reference-Apps
export SPRING_CLOUD_DEPLOYER_CLOUDFOUNDRY_SPACE=DEV
export SPRING_CLOUD_DEPLOYER_CLOUDFOUNDRY_DOMAIN=paasnpoa.bip.uk.fid-intl.com
export SPRING_CLOUD_DEPLOYER_CLOUDFOUNDRY_USERNAME=a496259@fil.com
export SPRING_CLOUD_DEPLOYER_CLOUDFOUNDRY_PASSWORD=Ashwin11
export SPRING_CLOUD_DEPLOYER_CLOUDFOUNDRY_SKIP_SSL_VALIDATION=false
export SPRING_CLOUD_DEPLOYER_CLOUDFOUNDRY_STREAM_SERVICES=myMessageStream_rabbitmq_server
```

**Comment by ericbottard** [comment]
If you're convinced this is a SSL issue with the maven repository, and you need a custom trustStore, then I think you need to have a look at the [java buildback](https://github.com/cloudfoundry/java-buildpack/blob/master/docs/framework-java_opts.md) configuration options (especially JAVA_OPTS that I linked), so that you can somehow pass JVM args to the Dataflow server. The problem, of course, is that you'll need to somehow make the store file available to the server as well (maybe embed it in your custom Dataflow Server build?)

Do you have other Cloud Foundry applications that use this maven repo? How do you deal with it usually?

**Comment by ashwgupt** [comment]
Yes, all of our Cloud Foundry applications use the maven repo and I can try using passing the MAVEN_OPTS content into JAVA_OPTS in manifest. But given there is no manifest used to run the Dataflow Server I never tried it. However for other application we don't need to access the maven repo from Cloud Foundry, as we push the packages JAR/WAR to the PCF.

Also, given am running the Dataflow Server for Cloud Foundry **locally** - http://docs.spring.io/spring-cloud-dataflow-server-cloudfoundry/docs/current-SNAPSHOT/reference/htmlsingle/#_running_the_server_app_locally, am unsure how much help can the manifest provide.

If you believe that, creating a manifest file but still using `java -jar spring-cloud-dataflow-server-cloudfoundry-1.1.0.BUILD-SNAPSHOT.jar` command to start the DFS can solve it, I can try it. Please advise.

**Comment by ericbottard** [comment]
Actually, if you are running the dataflow cf server **locally**, this is even easier I guess. I believe passing JVM options with `-D` (like `-Djavax.net.ssl.keyStore=` etc) is what you're looking for

**Comment by ashwgupt** [comment]
...and that is what I've bene doing but for some reason the app start up fails.

The packaging of application works fine and I have the fat jar file in hands but the `java -jar` command fails with the mentioned error and am unsure why the server start up is looking for the Maven repo (if it is at all).

As the logs don't indicate which `https` endpoint the app attempted and failed, there is not clarity on it And I might be totally wrong with my assumption of it being the Maven repo. Would need your help to know which else then.

**Comment by ashwgupt** [comment]
On the other note, can you please advise if the env var `MAVEN_REMOTE_REPOSITORIES_REPO1_URL` is at all required in this case when running the dataflow cf server locally? 

If yes, why? It should read the repo location from the local maven settings, shouldn't it.

**Comment by ashwgupt** [comment]
Issue is fixed with the help of skipping the SSL validation, which was a rather silly mistake to make.

However a better reported log message may have helped identify the https endpoint faster that has caused the exception and failure in startup.

I leave is for your decision. Closing this issue now.

**Comment by ashwgupt** [comment]
Reopening the issue, as it appears the above fix has only solved one step and causing similar issue at later stage.

The dataflow server cf start-up is now working. Registration of required apps also worked with below commands:
```
> app register --name task-processor --type processor --uri maven://org.springframework.cloud.stream.app:tasklaunchrequest-transform-processor-rabbit:jar:1.1.0.BUILD-SNAPSHOT
> app register --name task-launcher-local --type sink --uri maven://org.springframework.cloud.stream.app:task-launcher-local-sink-rabbit:jar:1.0.4.RELEASE
``` 

But this time the stream deployment fails, and thankfully the error message is clearly about it being the SSL handshake failure with the Maven repo while transferring the resources:
```
Caused by: org.eclipse.aether.transfer.ArtifactTransferException: Could not transfer artifact org.springframework.cloud.stream.app:task-launcher-local-sink-rabbit:jar:1.0.4.RELEASE from/to REPO1_URL (https://ftl.abc-intl.com:8443/NEXUS): sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
       	at org.eclipse.aether.connector.basic.ArtifactTransportListener.transferFailed(ArtifactTransportListener.java:43) ~[aether-connector-basic-1.0.2.v20150114.jar!/:na]
       	at org.eclipse.aether.connector.basic.BasicRepositoryConnector$TaskRunner.run(BasicRepositoryConnector.java:355) ~[aether-connector-basic-1.0.2.v20150114.jar!/:na]
       	at org.eclipse.aether.util.concurrency.RunnableErrorForwarder$1.run(RunnableErrorForwarder.java:67) ~[aether-util-1.0.2.v20150114.jar!/:na]
       	at org.eclipse.aether.connector.basic.BasicRepositoryConnector$DirectExecutor.execute(BasicRepositoryConnector.java:581) ~[aether-connector-basic-1.0.2.v20150114.jar!/:na]
       	at org.eclipse.aether.connector.basic.BasicRepositoryConnector.get(BasicRepositoryConnector.java:249) ~[aether-connector-basic-1.0.2.v20150114.jar!/:na]
       	at org.eclipse.aether.internal.impl.DefaultArtifactResolver.performDownloads(DefaultArtifactResolver.java:520) ~[aether-impl-1.0.2.v20150114.jar!/:na]
       	at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolve(DefaultArtifactResolver.java:421) ~[aether-impl-1.0.2.v20150114.jar!/:na]
       	... 81 common frames omitted
```

The remote repo is setup with the help of local variable `MAVEN_REMOTE_REPOSITORIES_REPO1_URL` but it's unclear where to pass the *trustStore* information along.

Any pointers please?

**Comment by ashwgupt** [comment]
FYI - I've attempted packaging the trustStore in the dataflow server cf application and setting javax system properties to make it available for use but it doesn't seem to make a difference

```
Resource resource = resourceLoader.getResource(trustStorePath);
System.setProperty("javax.net.ssl.trustStore", resource.getFile().getCanonicalPath());
System.setProperty("javax.net.ssl.trustStorePassword", trustStorePassword);
```

**Comment by ericbottard** [comment]
I still don't understand your environment fully. You said you were running ths dataflow-cloudfoundry-server locally (eg on a laptop). If that is indeed correct, why don't you pass `-D` properties to the JVM. What is this code above?

**Comment by ashwgupt** [comment]
Sorry for any confusion and let me simplify it.

I have a use case to deploy my Stream application to our private Cloud Foundry environment. The stream application is meant to listen on a RabbitMq queue and trigger a task, as defined in the stream.

To achieve the same, am using dataflow-server-cloudfoundry by running it locally on my Mac.

Below are the set of commands used to achieve it:-

* Set Maven remote repo
`export MAVEN_REMOTE_REPOSITORIES_REPO1_URL=https://ftl.abc.com/NEXUS`
* Setup Cloud Foundry destination -
```
export SPRING_CLOUD_DEPLOYER_CLOUDFOUNDRY_URL=https://api.paas.abc-intl.com/
export SPRING_CLOUD_DEPLOYER_CLOUDFOUNDRY_ORG=Paas-Apps
export SPRING_CLOUD_DEPLOYER_CLOUDFOUNDRY_SPACE=DEV
export SPRING_CLOUD_DEPLOYER_CLOUDFOUNDRY_DOMAIN=paas.abc-intl.com
export SPRING_CLOUD_DEPLOYER_CLOUDFOUNDRY_USERNAME=abc@xyz.com
export SPRING_CLOUD_DEPLOYER_CLOUDFOUNDRY_PASSWORD=password
export SPRING_CLOUD_DEPLOYER_CLOUDFOUNDRY_SKIP_SSL_VALIDATION=true
export SPRING_CLOUD_DEPLOYER_CLOUDFOUNDRY_STREAM_SERVICES=rabbitmq_server
```
* Start Dataflow Server -
  1. Build [Dataflow Server CF](https://github.com/spring-cloud/spring-cloud-dataflow-server-cloudfoundry)
  1. Start DF Server CF locally - `java -jar spring-cloud-dataflow-server-cloudfoundry-1.1.0.BUILD-SNAPSHOT.jar`
* Start DF Shell
* Import starter apps - `app import --uri http://bit.ly/stream-applications-rabbit-maven`
* Register apps - 
  1. `app register --name task-processor --type processor --uri maven://org.springframework.cloud.stream.app:tasklaunchrequest-transform-processor-rabbit:jar:1.1.0.BUILD-SNAPSHOT`
  1. `app register --name task-launcher-local --type sink --uri maven://org.springframework.cloud.stream.app:task-launcher-local-sink-rabbit:jar:1.0.4.RELEASE`
* Create & Deploy Stream - 
    `stream create myMessageStream --definition "rabbit --rabbit.queues=cloud-stream-source --rabbit.requeue=true --spring.rabbitmq.host=host.abc.com --spring.rabbitmq.port=5672 --spring.cloud.stream.bindings.output.contentType='text/plain' | task-processor --uri=maven://com.example:thumbnail-generator:0.0.1-SNAPSHOT | task-launcher-local" --deploy`

All of it works fine up until the last step, where the deployment of Stream fails with the SSL Handshake error with Maven.

I hope it makes it clearer. Please let me know if needs any further clarification.

**Comment by ericbottard** [comment]
OK, so I understood correctly. Change
> Start DF Server CF locally - java -jar spring-cloud-dataflow-server-cloudfoundry-1.1.0.BUILD-SNAPSHOT.jar

to something like 
Start DF Server CF locally - `java -Djavax.net.ssl.trustStore=xxx -Djavax.net.ssl.trustStorePassword=yyy -jar spring-cloud-dataflow-server-cloudfoundry-1.1.0.BUILD-SNAPSHOT.jar`

HTH

**Comment by ashwgupt** [comment]
Wonderful! It does. Thanks a lot!

My deployment is failing for timeout exception though, but that's something I will debug now.

However am unsure when this worked when passed as command line, why didn't my System.setProperties command work.

**Comment by ericbottard** [comment]
Glad I could help
